// front/pages/ProfilePage.tsx
import React, { useState, useRef } from 'react';
import { User } from '../types';
import RealApi from '../services/realApi';
import { Button, PageContainer, Input } from '../components/Shared';
import { User as UserIcon, Mail, Phone, Save, X, Edit2, Camera, Bell } from 'lucide-react';

interface ProfilePageProps {
  user: User;
  onUserUpdate: (user: User) => void;
}

export const ProfilePage: React.FC<ProfilePageProps> = ({ user, onUserUpdate }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  
  // Phone mask utility
  const formatPhoneNumber = (value: string) => {
    const numbers = value.replace(/\D/g, '');
    if (numbers.length === 0) return '';
    
    // US Format logic for <= 10 digits
    if (numbers.length <= 10) {
        if (numbers.length <= 3) return numbers;
        if (numbers.length <= 6) return `(${numbers.slice(0, 3)}) ${numbers.slice(3)}`;
        return `(${numbers.slice(0, 3)}) ${numbers.slice(3, 6)}-${numbers.slice(6)}`;
    }
    
    // 11 Digit (China Mobile style / Generic Intl)
    return `${numbers.slice(0, 3)} ${numbers.slice(3, 7)} ${numbers.slice(7, 11)}`;
  };

  const [formData, setFormData] = useState({
    name: user.name,
    email: user.email || '',
    phone: formatPhoneNumber(user.phone || ''),
    emailNotifications: user.notificationPreferences?.email ?? true,
    pushNotifications: user.notificationPreferences?.push ?? true
  });
  const [errors, setErrors] = useState<Record<string, string>>({});

  const fileInputRef = useRef<HTMLInputElement>(null);

  const validateField = (name: string, value: string) => {
    let error = '';
    
    switch (name) {
        case 'name':
            if (!value.trim()) error = 'Full name is required';
            break;
        case 'email':
            if (!value.trim()) error = 'Email is required';
            else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) error = 'Invalid email format';
            break;
        case 'phone':
            const rawPhone = value.replace(/\D/g, '');
            if (rawPhone.length > 0 && rawPhone.length < 10) error = 'Phone number must be at least 10 digits';
            break;
    }
    return error;
  };

  const handleChange = (name: keyof typeof formData, value: any) => {
    let finalValue = value;
    
    // Apply mask for phone
    if (name === 'phone' && typeof value === 'string') {
        const raw = value.replace(/\D/g, '');
        // Prevent excessively long numbers
        if (raw.length > 11) return; 
        finalValue = formatPhoneNumber(raw);
    }

    setFormData(prev => ({ ...prev, [name]: finalValue }));

    // Real-time validation for string fields
    if (typeof finalValue === 'string') {
        const error = validateField(name, finalValue);
        setErrors(prev => {
            const newErrors = { ...prev };
            if (error) newErrors[name] = error;
            else delete newErrors[name];
            return newErrors;
        });
    }
  };

  const validateAll = () => {
      const newErrors: Record<string, string> = {};
      const nameError = validateField('name', formData.name);
      if (nameError) newErrors.name = nameError;
      
      const emailError = validateField('email', formData.email);
      if (emailError) newErrors.email = emailError;
      
      const phoneError = validateField('phone', formData.phone);
      if (phoneError) newErrors.phone = phoneError;

      setErrors(newErrors);
      return Object.keys(newErrors).length === 0;
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateAll()) return;

    setIsLoading(true);
    try {
      const updatedUser = await RealApi.updateUserProfile(user.id, {
          name: formData.name,
          email: formData.email,
          phone: formData.phone.replace(/\D/g, ''), // Save raw digits
          notificationPreferences: {
              email: formData.emailNotifications,
              push: formData.pushNotifications
          }
      });
      onUserUpdate(updatedUser);
      setIsEditing(false);
      alert('Profile updated successfully!');
    } catch (error) {
      alert('Failed to update profile');
    } finally {
      setIsLoading(false);
    }
  };

  const handleCancel = () => {
    setFormData({
      name: user.name,
      email: user.email || '',
      phone: formatPhoneNumber(user.phone || ''),
      emailNotifications: user.notificationPreferences?.email ?? true,
      pushNotifications: user.notificationPreferences?.push ?? true
    });
    setErrors({});
    setIsEditing(false);
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
        alert('Please upload an image file.');
        return;
    }

    setIsLoading(true);
    try {
        const newPhotoUrl = await RealApi.uploadUserProfilePicture(user.id, file);
        onUserUpdate({ ...user, profilePicture: newPhotoUrl });
        alert('Profile picture updated!');
    } catch (error) {
        alert('Failed to upload profile picture.');
    } finally {
        setIsLoading(false);
    }
  };

  const triggerFileInput = () => {
    fileInputRef.current?.click();
  };

  return (
    <PageContainer title="My Profile">
      <div className="max-w-2xl mx-auto bg-white rounded-xl shadow-sm border overflow-hidden">
        {/* Header */}
        <div className="bg-brand-600 px-6 py-8 text-white text-center">
          <div className="relative inline-block group">
              <div className="h-24 w-24 bg-white rounded-full mx-auto flex items-center justify-center text-brand-600 text-3xl font-bold border-4 border-brand-200 mb-4 shadow-lg overflow-hidden">
                {user.profilePicture ? (
                    <img src={user.profilePicture} alt={user.name} className="w-full h-full object-cover" />
                ) : (
                    user.name.charAt(0)
                )}
              </div>
              <button 
                onClick={triggerFileInput}
                disabled={isLoading}
                className="absolute bottom-4 right-0 bg-white text-gray-700 p-2 rounded-full shadow-md hover:bg-gray-100 focus:outline-none transition-colors"
                title="Change Profile Picture"
              >
                  <Camera className="h-4 w-4" />
              </button>
              <input 
                 type="file" 
                 ref={fileInputRef} 
                 className="hidden" 
                 accept="image/*"
                 onChange={handleFileChange}
              />
          </div>
          <h2 className="text-2xl font-bold">{user.name}</h2>
          <p className="text-brand-100 font-medium">@{user.username} • {user.role.replace('_', ' ')}</p>
        </div>

        {/* Content */}
        <div className="p-8">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-bold text-gray-900">Personal Information</h3>
            {!isEditing && (
              <Button variant="outline" size="sm" onClick={() => setIsEditing(true)}>
                <Edit2 className="h-4 w-4 mr-2" /> Edit Profile
              </Button>
            )}
          </div>

          {isEditing ? (
            <form onSubmit={handleSave} className="space-y-8">
              <div className="space-y-4">
                  <Input 
                    label="Full Name"
                    value={formData.name}
                    onChange={(e) => handleChange('name', e.target.value)}
                    error={errors.name}
                    disabled={isLoading}
                  />
                  <Input 
                    type="email"
                    label="Email Address"
                    value={formData.email}
                    onChange={(e) => handleChange('email', e.target.value)}
                    error={errors.email}
                    disabled={isLoading}
                  />
                  <Input 
                    type="tel"
                    label="Phone Number"
                    value={formData.phone}
                    onChange={(e) => handleChange('phone', e.target.value)}
                    error={errors.phone}
                    placeholder="(555) 123-4567"
                    disabled={isLoading}
                  />
              </div>

              {/* Notification Preferences */}
              <div className="pt-6 border-t border-gray-100">
                  <h3 className="text-xl font-bold text-gray-900 mb-4">Notification Preferences</h3>
                  <div className="space-y-4">
                      <div className="flex items-center justify-between">
                          <div className="flex flex-col">
                              <span className="text-sm font-medium text-gray-900">Email Notifications</span>
                              <span className="text-sm text-gray-500">Receive updates and reminders via email.</span>
                          </div>
                          <button 
                            type="button" 
                            disabled={isLoading}
                            onClick={() => handleChange('emailNotifications', !formData.emailNotifications)}
                            className={`relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 ${formData.emailNotifications ? 'bg-brand-600' : 'bg-gray-200'}`}
                          >
                            <span aria-hidden="true" className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${formData.emailNotifications ? 'translate-x-5' : 'translate-x-0'}`}></span>
                          </button>
                      </div>

                      <div className="flex items-center justify-between">
                          <div className="flex flex-col">
                              <span className="text-sm font-medium text-gray-900">Push Notifications</span>
                              <span className="text-sm text-gray-500">Receive real-time alerts on your device.</span>
                          </div>
                           <button 
                            type="button" 
                            disabled={isLoading}
                            onClick={() => handleChange('pushNotifications', !formData.pushNotifications)}
                            className={`relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 ${formData.pushNotifications ? 'bg-brand-600' : 'bg-gray-200'}`}
                          >
                            <span aria-hidden="true" className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${formData.pushNotifications ? 'translate-x-5' : 'translate-x-0'}`}></span>
                          </button>
                      </div>
                  </div>
              </div>

              <div className="flex justify-end space-x-3 pt-6 border-t border-gray-100">
                <Button type="button" variant="secondary" onClick={handleCancel} disabled={isLoading}>
                  <X className="h-4 w-4 mr-2" /> Cancel
                </Button>
                <Button type="submit" disabled={isLoading}>
                  <Save className="h-4 w-4 mr-2" /> {isLoading ? 'Saving...' : 'Save Changes'}
                </Button>
              </div>
            </form>
          ) : (
            <div className="space-y-8">
              <div className="space-y-6">
                <div className="flex items-center p-4 bg-gray-50 rounded-lg border border-gray-100">
                    <div className="h-10 w-10 bg-white rounded-full flex items-center justify-center text-gray-400 shadow-sm mr-4">
                    <UserIcon className="h-5 w-5" />
                    </div>
                    <div>
                    <p className="text-sm font-medium text-gray-500">Full Name</p>
                    <p className="text-lg font-semibold text-gray-900">{user.name}</p>
                    </div>
                </div>

                <div className="flex items-center p-4 bg-gray-50 rounded-lg border border-gray-100">
                    <div className="h-10 w-10 bg-white rounded-full flex items-center justify-center text-gray-400 shadow-sm mr-4">
                    <Mail className="h-5 w-5" />
                    </div>
                    <div>
                    <p className="text-sm font-medium text-gray-500">Email Address</p>
                    <p className="text-lg font-semibold text-gray-900">{user.email || <span className="text-gray-400 italic">Not provided</span>}</p>
                    </div>
                </div>

                <div className="flex items-center p-4 bg-gray-50 rounded-lg border border-gray-100">
                    <div className="h-10 w-10 bg-white rounded-full flex items-center justify-center text-gray-400 shadow-sm mr-4">
                    <Phone className="h-5 w-5" />
                    </div>
                    <div>
                    <p className="text-sm font-medium text-gray-500">Phone Number</p>
                    <p className="text-lg font-semibold text-gray-900">{formatPhoneNumber(user.phone || '') || <span className="text-gray-400 italic">Not provided</span>}</p>
                    </div>
                </div>
              </div>

              <div className="pt-6 border-t border-gray-100">
                  <h3 className="text-xl font-bold text-gray-900 mb-4">Notification Preferences</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="flex items-center p-4 bg-gray-50 rounded-lg border border-gray-100 justify-between">
                          <div className="flex items-center">
                              <Bell className="h-5 w-5 text-gray-400 mr-3" />
                              <span className="font-medium text-gray-900">Email Updates</span>
                          </div>
                          <span className={`px-2.5 py-0.5 rounded-full text-xs font-medium ${user.notificationPreferences?.email !== false ? 'bg-green-100 text-green-800' : 'bg-gray-200 text-gray-600'}`}>
                              {user.notificationPreferences?.email !== false ? 'Enabled' : 'Disabled'}
                          </span>
                      </div>
                      <div className="flex items-center p-4 bg-gray-50 rounded-lg border border-gray-100 justify-between">
                          <div className="flex items-center">
                              <Bell className="h-5 w-5 text-gray-400 mr-3" />
                              <span className="font-medium text-gray-900">Push Notifications</span>
                          </div>
                          <span className={`px-2.5 py-0.5 rounded-full text-xs font-medium ${user.notificationPreferences?.push !== false ? 'bg-green-100 text-green-800' : 'bg-gray-200 text-gray-600'}`}>
                              {user.notificationPreferences?.push !== false ? 'Enabled' : 'Disabled'}
                          </span>
                      </div>
                  </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </PageContainer>
  );
};

// front/src/pages/ProfilePage.vue
<template>
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">
    <header class="bg-brand-600 text-white rounded-2xl p-8 shadow-sm flex flex-col items-center gap-4">
      <div class="relative">
        <div class="w-28 h-28 rounded-full bg-white text-brand-600 flex items-center justify-center text-3xl font-bold ring-4 ring-brand-400 overflow-hidden">
          <img v-if="form.profilePicture" :src="form.profilePicture" alt="头像" class="w-full h-full object-cover" />
          <span v-else>{{ userInitial }}</span>
        </div>
        <label class="absolute bottom-1 right-1 bg-white text-gray-600 p-2 rounded-full shadow cursor-pointer hover:bg-gray-100">
          <input type="file" class="hidden" accept="image/*" @change="handleAvatarUpload" />
          <span class="text-xs font-medium">更新</span>
        </label>
      </div>
      <div class="text-center space-y-1">
        <h1 class="text-2xl font-bold">{{ form.name || user?.name }}</h1>
        <p class="text-brand-100">@{{ user?.username }}</p>
      </div>
      <button class="btn-secondary" v-if="!isEditing" @click="startEdit">
        编辑资料
      </button>
    </header>

    <section class="bg-white rounded-2xl shadow-sm border p-8 space-y-6">
      <div class="flex items-center justify-between">
        <h2 class="text-xl font-semibold text-gray-900">个人信息</h2>
        <div class="space-x-3" v-if="isEditing">
          <button class="btn-secondary" @click="cancelEdit">取消</button>
          <button class="btn-primary" :disabled="saving" @click="saveProfile">
            {{ saving ? '保存中…' : '保存' }}
          </button>
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <FormField label="姓名" :error="errors.name">
          <input v-model="form.name" :disabled="!isEditing" type="text" class="input" />
        </FormField>
        <FormField label="邮箱" :error="errors.email">
          <input v-model="form.email" :disabled="!isEditing" type="email" class="input" />
        </FormField>
        <FormField label="手机号" :error="errors.phone">
          <input v-model="form.phone" :disabled="!isEditing" type="tel" class="input" placeholder="166 1234 5678" />
        </FormField>
        <div>
          <p class="text-sm font-medium text-gray-700 mb-2">通知设置</p>
          <div class="space-y-2">
            <label class="flex items-center gap-3 text-sm">
              <input type="checkbox" v-model="form.notificationPreferences.email" :disabled="!isEditing" class="toggle" />
              邮件通知
            </label>
            <label class="flex items-center gap-3 text-sm">
              <input type="checkbox" v-model="form.notificationPreferences.push" :disabled="!isEditing" class="toggle" />
              推送通知
            </label>
          </div>
        </div>
      </div>
    </section>

    <section class="bg-white rounded-2xl shadow-sm border p-8 space-y-6">
      <h2 class="text-xl font-semibold text-gray-900">安全活动</h2>
      <ul class="divide-y divide-gray-200">
        <li class="py-3 text-sm text-gray-600 flex items-center justify-between">
          <div>
            <p class="font-medium text-gray-900">最近登录</p>
            <p class="text-xs text-gray-500">{{ lastLogin }}</p>
          </div>
          <span class="text-green-600 text-xs font-semibold">安全</span>
        </li>
        <li class="py-3 text-sm text-gray-600 flex items-center justify-between">
          <div>
            <p class="font-medium text-gray-900">账户状态</p>
            <p class="text-xs text-gray-500 capitalize">{{ user?.status }}</p>
          </div>
          <span class="text-gray-500 text-xs">如需变更请联系管理员</span>
        </li>
      </ul>
    </section>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch, defineComponent, h } from 'vue';
import { useRouter } from 'vue-router';
import RealApi from '@/services/realApi';
import type { User } from '@/types';
import { useUserStore } from '@/stores/user';

const router = useRouter();
const { user, setUser } = useUserStore();

const digitsOnly = (value: string) => value.replace(/\D/g, '');

const formatPhone = (value: string) => {
  const digits = digitsOnly(value);
  if (!digits) return '';
  if (digits.length <= 3) return digits;
  if (digits.length <= 7) return `${digits.slice(0, 3)} ${digits.slice(3)}`;
  return `${digits.slice(0, 3)} ${digits.slice(3, 7)} ${digits.slice(7, 11)}`;
};

const isEditing = ref(false);
const saving = ref(false);
const form = reactive({
  name: '',
  email: '',
  phone: '',
  profilePicture: '',
  notificationPreferences: {
    email: true,
    push: true,
  },
});

const errors = reactive<Record<string, string>>({});

const userInitial = computed(() => user.value?.name?.charAt(0) ?? '?');
const lastLogin = new Date(Date.now() - 60 * 60 * 1000).toLocaleString();

watch(
  () => user.value,
  (val) => {
    if (!val) {
      router.push('/login');
      return;
    }
    form.name = val.name;
    form.email = val.email || '';
    form.phone = formatPhone(val.phone || '');
    form.profilePicture = val.profilePicture || '';
    form.notificationPreferences = {
      email: val.notificationPreferences?.email ?? true,
      push: val.notificationPreferences?.push ?? true,
    };
  },
  { immediate: true },
);

const startEdit = () => {
  isEditing.value = true;
};

const cancelEdit = () => {
  isEditing.value = false;
  errors.name = '';
  errors.email = '';
  errors.phone = '';
  if (user.value) {
    form.name = user.value.name;
    form.email = user.value.email || '';
    form.phone = formatPhone(user.value.phone || '');
    form.notificationPreferences.email = user.value.notificationPreferences?.email ?? true;
    form.notificationPreferences.push = user.value.notificationPreferences?.push ?? true;
  }
};

const validate = () => {
  errors.name = form.name.trim() ? '' : '姓名不能为空';
  errors.email = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email) ? '' : '请输入有效邮箱';
  const rawPhone = digitsOnly(form.phone);
  errors.phone = rawPhone.length && rawPhone.length < 10 ? '手机号至少 10 位' : '';
  return !errors.name && !errors.email && !errors.phone;
};

const saveProfile = async () => {
  if (!user.value || !validate()) return;
  saving.value = true;
  try {
    const updated = await RealApi.updateUserProfile(user.value.id, {
      name: form.name.trim(),
      email: form.email.trim(),
      phone: digitsOnly(form.phone),
      notificationPreferences: { ...form.notificationPreferences },
    });
    setUser(updated);
    isEditing.value = false;
    alert('个人资料已更新');
  } catch (error: any) {
    alert(error?.message || '保存失败');
  } finally {
    saving.value = false;
  }
};

const handleAvatarUpload = async (event: Event) => {
  if (!user.value) return;
  const files = (event.target as HTMLInputElement).files;
  if (!files?.length) return;
  const file = files[0];
  if (!file.type.startsWith('image/')) {
    alert('请上传图片文件');
    return;
  }
  try {
    const url = await RealApi.uploadUserProfilePicture(user.value.id, file);
    form.profilePicture = url;
    setUser({ ...(user.value as User), profilePicture: url });
  } catch (error) {
    alert('上传失败，请重试');
  }
};

const FormField = defineComponent({
  props: {
    label: String,
    error: String,
  },
  setup(props, { slots }) {
    return () =>
      h(
        'label',
        { class: 'flex flex-col gap-2 text-sm text-gray-700' },
        [
          props.label ? h('span', { class: 'font-medium' }, props.label) : null,
          slots.default?.(),
          props.error ? h('small', { class: 'text-xs text-red-500' }, props.error) : null,
        ],
      );
  },
});
</script>

<style scoped>
.input {
  @apply w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500 disabled:bg-gray-50;
}
.btn-primary {
  @apply inline-flex items-center justify-center rounded-lg bg-brand-600 text-white font-medium px-4 py-2 hover:bg-brand-700 transition focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-500 disabled:opacity-60;
}
.btn-secondary {
  @apply inline-flex items-center justify-center rounded-lg border border-white/40 text-white font-medium px-4 py-2 hover:bg-white/10 transition;
}
.toggle {
  @apply h-4 w-4 rounded border-gray-300 text-brand-600 focus:ring-brand-500;
}
</style>
